### ISSUE TITLE
Criação de página sobre 

### ISSUE THREAD

**Issue by LincolnCpsTest** [LincolnYuji/github-master#3]
Vocês poderiam criar uma página sobre? Agradeço

**Comment by LincolnYuji** [comment]
A página está em produção

**Comment by LincolnCpsTest** [comment]
Obrigado, estou aguardando.

[cid:image001.jpg@01D5A9BA.F5CB4BD0]<https://urldefense.proofpoint.com/v2/url?u=http-3A__www.cpsti.com.br_&d=DwMFAw&c=7my1DiYA8Epq5UwiA7n6nQ&r=AUo5qssxGMcxp_ylQH9d7HyiWb5OTz0ON5jtjFk2RFXXStfJMA4JaanYd-c_MoeM&m=cuLM2PXMWJT876ei51BFkNUaseaOVvYjke8DHvPC3qs&s=V-9N7oPKsR9XiEK9y14BYty1hNt8r9c0QGpo8CFG3-g&e=>
Lincoln Yuji Tsubamoto

Analista Desenvolvedor
(19) 3512.8769

lincoln.tsubamoto@cpsti.net.br<mailto:lincoln.tsubamoto@cpsti.net.br>
www.cpsti.com.br<https://urldefense.proofpoint.com/v2/url?u=http-3A__www.cpsti.com.br_&d=DwMFAw&c=7my1DiYA8Epq5UwiA7n6nQ&r=AUo5qssxGMcxp_ylQH9d7HyiWb5OTz0ON5jtjFk2RFXXStfJMA4JaanYd-c_MoeM&m=cuLM2PXMWJT876ei51BFkNUaseaOVvYjke8DHvPC3qs&s=V-9N7oPKsR9XiEK9y14BYty1hNt8r9c0QGpo8CFG3-g&e=>


De: LincolnYuji <notifications@github.com>
Enviada em: terça-feira, 3 de dezembro de 2019 09:17
Para: LincolnYuji/github-master <github-master@noreply.github.com>
Cc: Lincoln Tsubamoto <lincoln.tsubamoto@cpsti.net.br>; Author <author@noreply.github.com>
Assunto: Re: [LincolnYuji/github-master] Criação de página sobre (#3)


A página está em produção

**Comment by LincolnCpsTest** [comment]
Você pode colocar seu telefone no site @LincolnYuji
